[package]
name = "leetcode"
version = "0.1.0"
authors = ["Julia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leetcode_prelude = { path = 'src/leetcode_prelude' }
rand = "0.7"
