[package]
name = "leetcode"
version = "0.1.0"
authors = ["Julia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
leetcode_prelude = { version = "0.1.0", path = "../leetcode_prelude" }
