name: Rust

on:
  push:
    branches: [ mod ]
  pull_request:
    branches: [ mod ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Linter
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
