name: CI
on:
  pull_request:
  push:
    branches:
    - master
    - staging
    - trying

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  rust-audit:
    name: Audit Rust vulnerabilities
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-audit
        use-tool-cache: true

    - run: cargo audit

  rust:
    name: Rust
    runs-on: ${{ matrix.os }}
    # env:
    #  CC: deny_c

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          
      - name: Format
        run: cargo fmt
        
      - name: Compile
        run: cargo test --no-run

      - name: Test
        run: cargo test
        
      - name: Run
        run: cargo run
