name: clippy

on:
  push:
    branches: [ mod ]
  pull_request:
    branches: [ mod ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
    - name: Linter
      run: cargo clippy --verbose

