name: clippy

on:
  push:
    branches: [ mod ]
  pull_request:
    branches: [ mod ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
    - name: Linter
      run: cargo clippy --verbose

