name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rust-rustfmt-check
      uses: mbrobbel/rustfmt-check@0.1.0
    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.5
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run
      run: cargo run
