name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}
    # env:
    #  CC: deny_c

    strategy:
      matrix:
        os: [windows-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust environment
        uses: raftario/setup-rust-action@v1.0.0
        with:
          rust-channel: stable
          profile: default
          cache: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run
        run: cargo run

      - run: cargo tree
