name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  rust-audit:
    name: Audit Rust vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          use-tool-cache: true

      - run: cargo audit

  rust:
    name: Rust
    runs-on: ${{ matrix.os }}
    # env:
    #  CC: deny_c

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [nightly, beta, stable]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust environment
        uses: raftario/setup-rust-action@v1.0.0
        with:
          # Rust channel (version) to use (defaults to stable)
          rust-channel: stable
          # Rust host to use (defaults to current platform)
          # rust-host: ${{ matrix.os }}
          # Rust target to compile for (defaults to none)
          # rust-target: none
          # Enable caching (anything but 'true' defaults to 'false')
          cache: true
          # Install rustfmt (anything but 'true' defaults to 'false')
          install-rustfmt: true
          # Install clippy (anything but 'true' defaults to 'false')
          install-clippy: true

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -W clippy::all

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run
        run: cargo run

      - run: cargo tree
